# permissions for end users to view clusterimagepullsecretmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterimagepullsecretmanager-viewer-role
rules:
- apiGroups:
  - cheiron.anny.co
  resources:
  - clusterimagepullsecretmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cheiron.anny.co
  resources:
  - clusterimagepullsecretmanagers/status
  verbs:
  - get
