# permissions for end users to edit clusterimagepullsecretmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterimagepullsecretmanager-editor-role
rules:
- apiGroups:
  - cheiron.anny.co
  resources:
  - clusterimagepullsecretmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cheiron.anny.co
  resources:
  - clusterimagepullsecretmanagers/status
  verbs:
  - get
