# permissions for end users to edit imagepullsecretmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecretmanager-editor-role
rules:
- apiGroups:
  - cheiron.anny.co
  resources:
  - imagepullsecretmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cheiron.anny.co
  resources:
  - imagepullsecretmanagers/status
  verbs:
  - get
