# permissions for end users to view imagepullsecretmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecretmanager-viewer-role
rules:
- apiGroups:
  - cheiron.anny.co
  resources:
  - imagepullsecretmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cheiron.anny.co
  resources:
  - imagepullsecretmanagers/status
  verbs:
  - get
