apiVersion: cheiron.anny.co/v1alpha1
kind: ImagePullSecretManager
metadata:
  name: imagepullsecretmanager-sample
spec:
  mode: ServiceAccount
  secrets:
    - name: docker-hub
      registry: https://index.docker.io/v1
      username: my-user
      password: my-password
      email: my-email
    - existingSecrefRef:
        name: gitlab-registry