// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterImagePullSecretManager) DeepCopyInto(out *ClusterImagePullSecretManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterImagePullSecretManager.
func (in *ClusterImagePullSecretManager) DeepCopy() *ClusterImagePullSecretManager {
	if in == nil {
		return nil
	}
	out := new(ClusterImagePullSecretManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterImagePullSecretManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterImagePullSecretManagerList) DeepCopyInto(out *ClusterImagePullSecretManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterImagePullSecretManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterImagePullSecretManagerList.
func (in *ClusterImagePullSecretManagerList) DeepCopy() *ClusterImagePullSecretManagerList {
	if in == nil {
		return nil
	}
	out := new(ClusterImagePullSecretManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterImagePullSecretManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterImagePullSecretManagerSpec) DeepCopyInto(out *ClusterImagePullSecretManagerSpec) {
	*out = *in
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]ImagePullSecretSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterImagePullSecretManagerSpec.
func (in *ClusterImagePullSecretManagerSpec) DeepCopy() *ClusterImagePullSecretManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterImagePullSecretManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterImagePullSecretManagerStatus) DeepCopyInto(out *ClusterImagePullSecretManagerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterImagePullSecretManagerStatus.
func (in *ClusterImagePullSecretManagerStatus) DeepCopy() *ClusterImagePullSecretManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterImagePullSecretManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretManager) DeepCopyInto(out *ImagePullSecretManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretManager.
func (in *ImagePullSecretManager) DeepCopy() *ImagePullSecretManager {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImagePullSecretManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretManagerList) DeepCopyInto(out *ImagePullSecretManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ImagePullSecretManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretManagerList.
func (in *ImagePullSecretManagerList) DeepCopy() *ImagePullSecretManagerList {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ImagePullSecretManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretManagerSpec) DeepCopyInto(out *ImagePullSecretManagerSpec) {
	*out = *in
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]ImagePullSecretSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretManagerSpec.
func (in *ImagePullSecretManagerSpec) DeepCopy() *ImagePullSecretManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretManagerStatus) DeepCopyInto(out *ImagePullSecretManagerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretManagerStatus.
func (in *ImagePullSecretManagerStatus) DeepCopy() *ImagePullSecretManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecretSpec) DeepCopyInto(out *ImagePullSecretSpec) {
	*out = *in
	out.ExistingSecretRef = in.ExistingSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecretSpec.
func (in *ImagePullSecretSpec) DeepCopy() *ImagePullSecretSpec {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecretSpec)
	in.DeepCopyInto(out)
	return out
}
